### ISSUE TITLE
Re: THIS CODE IS FUTILE WHEN THE JAVA VERIFICATION MECHANISIM OF KISSMANGA IS ENABLED (A 5 SEC WAIT TIME BEFORE THE HTTP SOURCE IS DISPLAYED. IF YOU HAVE A SOLUTION LET ME KNOW)

### ISSUE THREAD

**Issue by MrAmnesiac** [MohammadHakim/KissManga-Crawler#1]
Hi!

I'm pretty sure that happens because of cloudflare protections, you can, however, use this https://github.com/Anorov/cloudflare-scrape . I'm not sure how to implement it, but it might fix your problem.

**Comment by MohammadHakim** [comment]
Very interesting. I never thought of looking in Node, cause I was limiting myself to Python. Maybe I'll take a look at this some day
Thanks!

**Comment by MohammadHakim** [comment]
This works like a charm!
Thank you!

**Comment by MrAmnesiac** [comment]
I'm glad! :+1:
